# Generated by Django 5.0.6 on 2024-08-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_content_type_tag_object_id'),
    ]

    operations = [
    ]
