# Generated by Django 5.0.6 on 2024-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_preparation_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('portion', 'Portion'), ('people', 'People')], max_length=100),
        ),
    ]
